### ISSUE TITLE
installation or apk on readme 

### ISSUE THREAD

**Issue by alphaolomi** [godopetza/DINE_iO#1]
Hello @godopetza 

Nice project you got here, but no apk or installation instructions were provided  would be nice to have a picture or production ready apk

- Alpha

**Comment by godopetza** [comment]
Hello @alphaolomi, thank you for checking out my project.

It's been a while since I worked on this, but I will share some screens in the readme and offer an apk for it soon enough.

**Comment by alphaolomi** [comment]
Thank you in advance

**Comment by godopetza** [comment]
Currently, there is a demo video link in the readme file. You can check that out while I try to put up the apk. @alphaolomi

**Comment by godopetza** [comment]
Good day @alphaolomi, APK download link has been provided now, please check the readme file again. Looking forward to your comments before I close this issue.
